### 四分类

In [1]:
import pandas as pd
import numpy as np

data = pd.read_excel("/data/zhengtianlong/Private/Depressed/deptweet_dataset.xlsx")
data.head()

,id,tweet,replies_count,retweets_count,likes_count,target,label,confidence_score
0,16225710910,Whenever it gets close to my bday I always go ...,0,0,0,0,non-depressed,0.647
1,29511881849,". Yeah, I can see that. My stuff is not depres...",0,0,0,0,non-depressed,1.000
2,529081906474664000,My focus has been scattered lately between dif...,0,0,0,1,mild,1.000
3,653785271176002944,"I don't always think it equals depression, tho...",1,0,1,0,non-depressed,1.000
4,860078854601415936,That show was ghastly! It had such an air of w...,1,0,0,0,non-depressed,1.000

In [2]:
data = data.rename(columns = {"tweet":"text"})
data = data[['id', 'text', 'target', 'label']]
data.head()

,id,text,target,label
0,16225710910,Whenever it gets close to my bday I always go ...,0,non-depressed
1,29511881849,". Yeah, I can see that. My stuff is not depres...",0,non-depressed
2,529081906474664000,My focus has been scattered lately between dif...,1,mild
3,653785271176002944,"I don't always think it equals depression, tho...",0,non-depressed
4,860078854601415936,That show was ghastly! It had such an air of w...,0,non-depressed

In [3]:
data.to_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet.csv', index=False)
data = pd.read_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet.csv')
data.head(5)

,id,text,target,label
0,16225710910,Whenever it gets close to my bday I always go ...,0,non-depressed
1,29511881849,". Yeah, I can see that. My stuff is not depres...",0,non-depressed
2,529081906474664000,My focus has been scattered lately between dif...,1,mild
3,653785271176002944,"I don't always think it equals depression, tho...",0,non-depressed
4,860078854601415936,That show was ghastly! It had such an air of w...,0,non-depressed

In [4]:
data_0 = data[data['target'] == 0]
data_1 = data[data['target'] == 1]
data_2 = data[data['target'] == 2]
data_3 = data[data['target'] == 3]

print(len(data)==(len(data_0)+len(data_1)+len(data_2)+len(data_3)))

True

In [5]:
from sklearn.model_selection import train_test_split
def train_validate_test_split(df, seed = 7):
    train, valtest = train_test_split(df, test_size=0.1, random_state = seed)
    val, test = train_test_split(valtest, test_size = 0.35, random_state = seed)
    return train, val, test

train_df_0, valid_df_0, test_df_0 = train_validate_test_split(data_0)
train_df_1, valid_df_1, test_df_1 = train_validate_test_split(data_1)
train_df_2, valid_df_2, test_df_2 = train_validate_test_split(data_2)
train_df_3, valid_df_3, test_df_3 = train_validate_test_split(data_3)

train_df = pd.concat([train_df_0, train_df_1, train_df_2, train_df_3])
valid_df = pd.concat([valid_df_0, valid_df_1, valid_df_2, valid_df_3])
test_df = pd.concat([test_df_0, test_df_1, test_df_2, test_df_3])

print(len(data)==(len(train_df)+len(valid_df)+len(test_df)))

train_df.to_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet_train.csv', index=False)
valid_df.to_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet_valid.csv', index=False)
test_df.to_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet_test.csv', index=False)

True

In [6]:
print(set(data.label))
print(set(data.target))

{'mild', 'non-depressed', 'moderate', 'severe'}
{0, 1, 2, 3}

### 二分类

In [7]:
import pandas as pd

# 读取CSV文件
data = pd.read_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet_train.csv')

# 将target列中的2和3替换为1
data['target'] = data['target'].replace({2: 1, 3: 1})

# 将label列中的moderate和severe替换为mild
data['label'] = data['label'].replace({'moderate': 'mild', 'severe': 'mild'})

# 如果需要，可以将修改后的DataFrame保存回CSV
data.to_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet_train_binary.csv', index=False)

In [8]:
data = pd.read_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet_test.csv')

data['target'] = data['target'].replace({2: 1, 3: 1})
data['label'] = data['label'].replace({'moderate': 'mild', 'severe': 'mild'})
data.to_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet_test_binary.csv', index=False)

data = pd.read_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet_valid.csv')

data['target'] = data['target'].replace({2: 1, 3: 1})
data['label'] = data['label'].replace({'moderate': 'mild', 'severe': 'mild'})
data.to_csv('/data/zhengtianlong/Private/Depressed/Deptweet/Deptweet_valid_binary.csv', index=False)